version: '2'
services:
  mysql:
    image: mysql:8.0
    ports:
      - "3347:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: pyweb
    volumes:
      - mysql-vol:/var/lib/mysql

volumes:
  mysql-vol:
    driver: local